import type { Metadata } from "next";
import localFont from "next/font/local";

import { SocketProvider } from "@/providers/socket.provider";
import { ToastifyProvider } from "@/providers/toastify.provider";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
          <ToastifyProvider>
            <main className="w-full min-h-screen bg-slate-100 flex justify-center items-center">
              <section className="w-full bg-white rounded-xl border border-slate-200 shadow-md px-5 py-4 max-w-[400px]">
                {children}
              </section>
            </main>
          </ToastifyProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
