import { IBrand } from "../types/brand.type";

export const brands: Array<IBrand> = [
  {
    id: 992,
    code: "i-life",
    title_fa: "آی لایف",
    title_en: "i-Life",
  },
  {
    id: 10,
    code: "apple",
    title_fa: "اپل",
    title_en: "Apple",
  },
  {
    id: 6,
    code: "hp",
    title_fa: "اچ‌ پی",
    title_en: "HP",
  },
  {
    id: 1163,
    code: "alienware",
    title_fa: "الین ویر",
    title_en: "Alienware",
  },
  {
    id: 10397,
    code: "xpg",
    title_fa: "ای دیتا ایکس پی جی",
    title_en: "XPG",
  },
  {
    id: 3,
    code: "acer",
    title_fa: "ایسر",
    title_en: "Acer",
  },
  {
    id: 17043,
    code: "acer-predator",
    title_fa: "ایسر پریدیتور",
    title_en: "Acer Predator",
  },
  {
    id: 4,
    code: "asus",
    title_fa: "ایسوس",
    title_en: "ASUS",
  },
  {
    id: 29,
    code: "intel",
    title_fa: "اینتل",
    title_en: "Intel",
  },
  {
    id: 2526,
    code: "porsche-design",
    title_fa: "پورش دیزاین",
    title_en: "Porsche Design",
  },
  {
    id: 9,
    code: "toshiba",
    title_fa: "توشیبا",
    title_en: "Toshiba",
  },
  {
    id: 121,
    code: "glx",
    title_fa: "جی ال ایکس",
    title_en: "GLX",
  },
  {
    id: 2,
    code: "dell",
    title_fa: "دل",
    title_en: "Dell",
  },
  {
    id: 3931,
    code: "durabook",
    title_fa: "دورابوک",
    title_en: "Durabook",
  },
  {
    id: 34089,
    code: "decomas-new",
    title_fa: "دیکوماس",
    title_en: "Decomas",
  },
  {
    id: 91,
    code: "razer",
    title_fa: "ریزر",
    title_en: "Razer",
  },
  {
    id: 18,
    code: "samsung",
    title_fa: "سامسونگ",
    title_en: "Samsung",
  },
  {
    id: 11,
    code: "suzuki",
    title_fa: "سوزوکی",
    title_en: "Suzuki",
  },
  {
    id: 1,
    code: "sony",
    title_fa: "سونی",
    title_en: "Sony",
  },
  {
    id: 1662,
    code: "xiaomi",
    title_fa: "شیائومی",
    title_en: "Xiaomi",
  },
  {
    id: 5,
    code: "fujitsu",
    title_fa: "فوجیتسو",
    title_en: "Fujitsu",
  },
  {
    id: 7,
    code: "compaq",
    title_fa: "کامپک",
    title_en: "Compaq",
  },
  {
    id: 34700,
    code: "gateway",
    title_fa: "گیت‌وی",
    title_en: "Gateway",
  },
  {
    id: 34,
    code: "gigabyte",
    title_fa: "گیگابایت",
    title_en: "GIGABYTE",
  },
  {
    id: 94,
    code: "lenovo",
    title_fa: "لنوو",
    title_en: "Lenovo",
  },
  {
    id: 51,
    code: "microsoft",
    title_fa: "مایکروسافت",
    title_en: "Microsoft",
  },
  {
    id: 719,
    code: "miscellaneous",
    title_fa: "متفرقه",
    title_en: "Miscellaneous",
  },
  {
    id: 188,
    code: "vaio",
    title_fa: "وایو",
    title_en: "Vaio",
  },
  {
    id: 82,
    code: "huawei",
    title_fa: "هوآوی",
    title_en: "Huawei",
  },
];
