import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

const ContactUs: React.FC = () => {
  return <p>Contact us</p>;
};

export default ContactUs;
