import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Poppins } from "next/font/google";

import StyledComponentsProvider from "@/providers/styled-component.provider";

import "./globals.css";
import { ResponsiveAppBar } from "@/components/appbar";
import { MaterialUiProvider } from "@/providers/material.provider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sample App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MaterialUiProvider>
          <StyledComponentsProvider>
            {/* <Navbar /> */}
            <ResponsiveAppBar />
            {children}
          </StyledComponentsProvider>
        </MaterialUiProvider>
      </body>
    </html>
  );
}
